Drug-Drug Interaction
linqs/psl-examples pull request #18
Opened 2022-09-19 23:31 UTC by ThachAndrew

This PR is related to the issue in the main PSL [repo](https://github.com/linqs/psl).  ([Make Drug-Drug Prediction into a PSL Example #239 ](https://github.com/linqs/psl/issues/239) )

The zipped [data](https://drive.google.com/file/d/1nll2AZ13JLAsrp7r1xyTw7ozeHxXLHTS/view?usp=sharing) will need to be uploaded.

2022-09-20 00:35 UTC, eriq-augustine requested changes
Looking pretty good in-general.
I don't see any big issues.

---

Note that any comment (especially style comments) may apply more than once.
I will typically only make each comment once.

Run `./.ci/check_conventions.sh` and make sure you pass the CI checks.

Important: In the group meeting tomorrow, let's chat about what we should formally call this example.
There were other drug-based interaction papers that we published, so `drug-interation` may be too vague.
`drug-drug`? `drug-drug-interation`? `ddi`?

You can go ahead and add a `fetchData.sh` script and point it to the future location of the data.

Data comments:
 - The name of the zip file should be `drug-interaction.zip` (and should extract into `drug-interaction`).
 - Good job getting the extraction output directory pattern correct.
 - At least one data file (`data/general-interactions/00/eval/interacts_target.txt`) has lines that ends with a space character. I don't think there should be any space characters in your data files.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/DrugBankIDs
> +DB00121
According to the readme, this file maps drugbank ids to internal int ids.
Great idea to have this file, but needs two adjustments:
1) The integer id should also be included (so each line would have two items). This is useful if we ever want to include more drugs or take a subset.
2) This should live alongside the data, not the model.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +
Extra newline.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +In this example, we attempt to infer unknown DDIs from a network of
Expand "DDI".

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +Each dataset below  contain seven drug–drug similarities. Four of these
Double space.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +- general-interactions: This dataset came from DrugBank version 4.3 for a total of 4293 interactiosn across 315 drugs.  There is also a file DrugBankIDs, which maps integer IDs to DrugIDs.  Each fold
The line length in this file seems to vary a bit.
I would just not worry too much about line length in an MD file and break at grammatical points.
I usually break on sentences and clauses (if they are long).
You have probably already noticed this pattern in most of the communications (email, slack, etc).

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +Each dataset below  contain seven drug–drug similarities. Four of these
I think this section needs a little restructuring.
I would move the different dataset discussion to the first part, and then after that take a small paragraph to talk about the similarities.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +- general-interactions: This dataset came from DrugBank version 4.3 for a total of 4293 interactiosn across 315 drugs.  There is also a file DrugBankIDs, which maps integer IDs to DrugIDs.  Each fold
Use a comma to denote thousand (this is not a general rule, but since you did it for other numbers in this file).

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +https://linqs.org/publications/#id:sridhar-bio16
Put the title of the paper here and make that a link to what you currently have here.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +}
Put in a code (preformatted) block (use three tildes).
The bibtex also seems improperly formatted, just grab it straight from our site.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +## Keywords
Add `real data` and `weight learning`.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/cli/drug-interaction-eval.data
> +
Extra newline.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/cli/drug-interaction.psl
> +1: ATCSimilarity(D1, D2) & interacts(D1, D3) & validInteraction(D1, D3) & validInteraction(D2, D3) & (D2 - D3) & (D1 - D2)>>interacts(D2, D3) ^2
Use `!=` instead of `-`.
They work the same, it is just more modern style.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/cli/drug-interaction.psl
> +1: ATCSimilarity(D1, D2) & interacts(D1, D3) & validInteraction(D1, D3) & validInteraction(D2, D3) & (D2 - D3) & (D1 - D2)>>interacts(D2, D3) ^2
Use `->` instead of `>>`.
And make sure to always include a space around binary operators (except commas).

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/cli/drug-interaction.psl
> +//prior
Comments in code should always have a space after the comment token.

Also, some more comment notes that do not apply in this situation, just FYI:
 - Comments should typically be complete sentences.
 - In-line comments that occur after code should have two spaces before the comment token, e.g. `foo();  // Call foo.`.

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/README.md
> +https://linqs.org/publications/#id:sridhar-bio16
Also, add a sentence about how the data processing and model are taken directly from the paper/code (and link to the old repo).

2022-09-20 00:35 UTC, eriq-augustine commented on drug-interaction/cli/run.sh
> +#!/bin/bash
This file is actually generated using the [generate_scripts.py](https://github.com/linqs/psl-examples/blob/main/.templates/generate_scripts.py) script and [config options](https://github.com/linqs/psl-examples/blob/main/.templates/config.json).
This is so all examples get the same versions.

2022-09-27 21:42 UTC, ThachAndrew commented
Hello Eriq, I believe the changes are all done.  We just need to push the zipped data and maybe consider changing/disabling the weight learning.

2022-09-27 22:54 UTC, eriq-augustine requested changes
Making some good progress.

There are several repeat comments.
Make sure to double check that you address not just the exact comment, but everything that the comment applies to.
And if you have questions, be sure to ask.

The data archive should extract into a directory named "drug-drug-interaction" (and then the respective sub directories).
This will also need to be reflected in your .data files.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +- general-interactions: This dataset came from DrugBank version 4.3 for a total of 4,293 interactions across 315 drugs.  There is also a file DrugBankIDs, which maps integer IDs to DrugIDs.  Each fol
Double space.
Note that this is a repeat comment.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +The data came from the original [repo](https://bitbucket.org/linqs/psl-drug-interaction-prediction/src/master/).  Each fold contains ground atoms which have been preprocessed and dumped from the orig
Don't say that the data came from that repo.
Just say that the repo contains the original data and experiments from the paper.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +## Dataset
This sections needs a short introductory paragraph before launching into each dataset.
Maybe add a sentence about there being three different datasets derived from DrugBank (include a link), and then move the last paragraph in this section into this one.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +The default settings for the run script is for the dataset "general-interactions".  Therefore, the evaluator thresholds must be changed when running other datasets.
Give an example of changing the thresholds (just do it on the command line, not editing the file).

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +[A Probabilistic Approach for Collective Similarity-Based Drug-Drug Interaction Prediction](https://linqs.org/publications/#id:sridhar-bio16)
Use complete sentences.
Maybe something like: "This example is based on the work from ...".

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +The data came from the original [repo](https://bitbucket.org/linqs/psl-drug-interaction-prediction/src/master/).  Each fold contains ground atoms which have been preprocessed and dumped from the orig
Don't mention lower-level things like "ground atoms".
Instead, use higher-level wording like "data".

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +
Add a line about using this citation to reference the original work.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +
Double newline.
Repeat comment.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/cli/drug-drug-interaction.psl
> +5: validInteraction(D1,D2) -> ~interacts(D1,D2) ^2
Use a `!` instead of a `~`.

2022-09-27 22:54 UTC, eriq-augustine commented on drug-drug-interaction/cli/drug-drug-interaction-eval.data
> +   ATCsimilarity: ../data/general-interactions/00/eval/similarity_atc.txt
The path should be `../data/drug-drug-interaction/general-interactions/00/eval/similarity_atc.txt`.

2022-09-28 01:45 UTC, eriq-augustine requested changes
Looking better.
Still a few things.

2022-09-28 01:45 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +For example, `sed -i "s|threshold=[[:digit:]]\.[[:digit:]]*|threshold=<NEW_THRESHOLD>|g" run.sh`, will change the thresholds to NEW\_THRESHOLD.
Nope.
Command-line usage, not file editing.

2022-09-28 01:45 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +The default settings for the run script is for the dataset "general-interactions".  Therefore, the evaluator thresholds must be changed when running other datasets.
Double space.

2022-09-28 01:45 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +There are three datasets which are derived from [DrugBank 4.3](https://go.drugbank.com/downloads/archived) and [drugs.com](Drugs.com).
Still inconsistent line breaks (arbitrary breaks, clause breaks, and no breaks).
Pick one and stick with it.

2022-09-28 01:45 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +Each fold in this example contains data which have been preprocessed and dumped from the original experiment.
Just "This example ..." instead of "Each fold in this example ...".

2022-09-28 01:45 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +
Something like: "To reference the original work, please use this citation:".

2022-09-28 02:34 UTC, eriq-augustine approved these changes
Looks good to me!
Once we debug that weight learning issue, we can take this in.

2022-09-28 15:33 UTC, eriq-augustine requested changes
Missed one thing.

2022-09-28 15:33 UTC, eriq-augustine commented on .templates/config.json
> +        "evalOptions": "--infer --eval DiscreteEvaluator -D discreteevaluator.threshold=0.4",
Don't include `--infer` or `--learn`.

2022-09-28 22:55 UTC, eriq-augustine approved these changes
lgtm, let's just look into the WL issues.

2022-10-04 00:11 UTC, eriq-augustine requested changes
Just needs a README fix.

2022-10-04 00:11 UTC, eriq-augustine commented on drug-drug-interaction/README.md
> +For each dataset, we used a Guided Random Grid Search to tune the weights. This produces slightly better results than the original weight learning method. To produce the same results from the origina
This description needs work.
1) Search-based weight learners do not "tune" weights, they set or search over them (gradient-based approaches tune).
2) You don't mention the original weight learning method.
3) It is incorrect to say that using no weight learning reproduces the results from the paper, it only approximates them.

I suggest the following:
The original experiments this example is derived from uses an outdated weight learning method (MaxLikelihoodMPE).
This example replaces the outdated weight learning method with more modern methods that perform marginally better.
Using the default weights and disabling weight learning will also approximate the original results.

2022-10-04 00:52 UTC, eriq-augustine commented
lgtm!

2022-10-04 00:54 UTC, merged